name: Build ArcadePaper

on:
  push:
    branches: [ "ver/1.8.8" ]
  pull_request:
    branches: [ "ver/1.8.8" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: ./arcadepaper build
    - name: Compress
      run: tar -cvf build.tar ./*
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ArcadePaper Artifact
        path: build.tar
